#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KochBuch.Resource", IsApplication=true)]

namespace KochBuch
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Antipasti = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Bruschetta = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int De_EXOTISCHE = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int De_Grunkohl = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int De_KARTOFFELSUPPE = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int De_PUTEN = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int De_Rindsteak = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int De_SAUERKRAUT = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Deutschland = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int France = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Italien = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Kouskous = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Panna_Cotta = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Portugal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Risotto = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int romania = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Sp_Datteln_im_Speckmantel = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Sp_Garnelen_in_Knoblauch = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Sp_Gefuelltes_Rinderfilet_mediterran = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Sp_Papas_Arrugadas = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Sp_Rafis_Fisch_Paella = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Sp_Traditionelle_spanische_Tortilla = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Spain = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Tajin = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Tiramisu = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Tramezzini = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Turkei = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int Image = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int Img = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int LabelDauer = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int List1 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int Text = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int Text1 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Text2 = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int TxtDauer = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int TxtInhalt = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int TxtTitel = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int TxtZutaten = 2131034120;
			
			// aapt resource value: 0x7f050012
			public const int gridView1 = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int imageView1 = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int separator = 2131034115;
			
			// aapt resource value: 0x7f050011
			public const int textView1 = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int textView2 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int textView3 = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Board = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Deutschland = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Frankreich = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Italien = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ItemsLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Portugal = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Spanien = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int test = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Ticket = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Turkey = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
